-- Name: Jordan Kleinbaum & Carey Datre
-- Purpose: Group Project Part 3: DB Integration with Patient GUI
-- Date: December 13th, 2023

-- Create the PATIENT Table
CREATE TABLE PATIENT (
    PATIENTID INT PRIMARY KEY,
    FIRSTNAME VARCHAR2(255),
    LASTNAME VARCHAR2(255),
    ROOMNUMBER VARCHAR2(255),
    PATIENTTYPE VARCHAR2(255),
    ADDITIONALINFO VARCHAR2(255)
);

-- Create the PATIENTEVENTS Table
CREATE TABLE PATIENTEVENTS (
    PATIENTID INT,
    DESCRIPTION VARCHAR2(255),
    PAINLEVEL INT,
    FOREIGN KEY (PATIENTID) REFERENCES PATIENT(PATIENTID)
);

-- Insert Data Into the PATIENT Table
INSERT INTO PATIENT (PATIENTID, FIRSTNAME, LASTNAME, ROOMNUMBER, PATIENTTYPE, ADDITIONALINFO) VALUES (0, 'Jordan', 'Kleinbaum', '123', 'Patient', 'Great Student');
INSERT INTO PATIENT (PATIENTID, FIRSTNAME, LASTNAME, ROOMNUMBER, PATIENTTYPE, ADDITIONALINFO) VALUES (1, 'Carey', 'Datre', '124', 'Patient', 'Hard Worker');
INSERT INTO PATIENT (PATIENTID, FIRSTNAME, LASTNAME, ROOMNUMBER, PATIENTTYPE, ADDITIONALINFO) VALUES (2, 'Professor', 'Ezell', '125', 'Patient', 'Best Professor');

INSERT INTO PATIENT (PATIENTID, FIRSTNAME, LASTNAME, ROOMNUMBER, PATIENTTYPE, ADDITIONALINFO) VALUES (3, 'Joe', 'Biden', '126', 'InPatient', 'President');

INSERT INTO PATIENT (PATIENTID, FIRSTNAME, LASTNAME, ROOMNUMBER, PATIENTTYPE, ADDITIONALINFO) VALUES (4, 'Lionel', 'Messi', '127', 'OutPatient', 'Soccer Player');

-- Insert Data Into the PATIENTEVENTS Table with Formatted Date
INSERT INTO PATIENTEVENTS (PATIENTID, DESCRIPTION, PAINLEVEL) VALUES (0, 'Checkup', 2);
INSERT INTO PATIENTEVENTS (PATIENTID, DESCRIPTION, PAINLEVEL) VALUES (1, 'Surgery', 8);
INSERT INTO PATIENTEVENTS (PATIENTID, DESCRIPTION, PAINLEVEL) VALUES (2, 'Medication', 1);
INSERT INTO PATIENTEVENTS (PATIENTID, DESCRIPTION, PAINLEVEL) VALUES (3, 'Physical Therapy', 3);